In [2]:
import numpy as np
from multiprocessing import Pool
import time
# import math

In [2]:
# del(ar)

In [7]:
ar = np.random.rand(1*10**8, 5)

In [10]:
with Pool(5) as p:
    ts = time.monotonic()
    u = p.map(
        np.mean,
        [ar[:,0], ar[:,1], ar[:,2]]
        )
    te = time.monotonic()
    print(te-ts)

5.281645850000132


In [8]:
ts2 = time.monotonic()
z = (np.mean(ar[:,0]), np.mean(ar[:,1]), np.mean(ar[:,2]))
te2 = time.monotonic()
print(te2-ts2)

1.362557447000654


In [17]:
a = np.random.random(size=(3,4)) * 100
np.unravel_index(np.argsort(a, axis=None), shape=(3,4))

(array([0, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 1], dtype=int64),
 array([0, 1, 1, 2, 0, 3, 2, 2, 1, 3, 3, 0], dtype=int64))

In [18]:
a

array([[ 5.06752616,  8.12286646, 12.28115727, 53.68470546],
       [61.5426377 , 39.77893808, 38.67174059, 19.79147191],
       [16.34276311, 11.51452855, 31.34014915, 44.62405   ]])